CREATE TABLE prod_warehouse.time_dim (

)

INSERT INTO
SELECT
  FORMAT_TIMESTAMP('%T', t) AS time_id,
  EXTRACT(HOUR FROM t) AS hour,
  EXTRACT(MINUTE from t) AS minute,
  EXTRACT(SECOND from t) AS second
FROM (
  SELECT *
  FROM UNNEST(GENERATE_TIMESTAMP_ARRAY('2000-01-01 00:00:00', '2000-01-01 23:59:59', INTERVAL 1 SECOND)) AS t
)